### PR TITLE
Pipeline to build + test

### PR DESCRIPTION
**Pull request by pmengelbert**
This pipeline has been tested with every package, on every distro, on every architecture. All packages were successfully built, successfully tested, and passed the tests.

The only exception is Windows packages, which are not currently tested.

Following this, a pull request will be submitted to publish the tested packages to a storage account.

### CODE REVIEW

**Comment by cpuguy83** [comment]
Looks like signing is failing, but no bother I'd rather not run that as part of normal CI.

**Comment by cpuguy83** [comment]
Did these checks get run manually? How come it only shows windows?

**Comment by pmengelbert** [comment]
> Looks like signing is failing on Windows.

How does signing work on Windows? On Linux the signing usually gpg signs the deb/rpm package itself, and gets stored in the metadata, right? How does this work with the windows zip?

**Comment by pmengelbert** [comment]
> Did these checks get run manually? How come it only shows windows?

What do you mean?

I ran the tests for all distros/packages/arches using `moby-trigger`.

**Comment by pmengelbert** [comment]
Signing is working now, let me know if this PR needs anything else.

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
