### PR TITLE
Bump go version to 1.21.1 for go container

### PR DESCRIPTION
**Pull request by pmengelbert**
This is required for building moby-compose 2.22

### CODE REVIEW

**Comment by cpuguy83** [comment]
Let's do this bump just for compose.

**Comment by pmengelbert** [comment]
> Let's do this bump just for compose.

It took some doing since we didn't have a way to set the go version for individual packages. This is done

**Comment by pmengelbert** [comment]
Hold off on this, still needs to be tested.

**Comment by pmengelbert** [comment]
@cpuguy83 This is ready for review now

**Review by cpuguy83 — APPROVED** [review]

**Pull request merged**
